name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: create dummy wifi file
        run: |
          touch /home/runner/work/RP2040-HOTAS/RP2040-HOTAS/WIFI_CR
          echo '[wifi]\nAP=\n; LINUX\n	-D STASSID=\"AP\"\n	-D STAPSK=\"PASSWORD\"\n\n; WINDOWS\n;	-D STASSID="AP"\n;	-D STAPSK="PASSWORD"' > /home/runner/work/RP2040-HOTAS/RP2040-HOTAS/WIFI_CR
      - name: Build PlatformIO Project
        run: pio run
